name: ReviewGPT AI Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewgpt:
    runs-on: ubuntu-latest
    steps:
      - uses: reviewgpt-ai/reviewgpt-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 